url: http://overpass-api.de/api/interpreter
fname_rail: rail
fname_station: station
fname_city: city
columns_rail:
  name: str
columns_station:
  name: str
  network: str
columns_city:
  name: str
  place: str
  population: str
columns_heri:
  name: str
  heritage: str
